-- drop all table at once

DROP TABLE IF EXISTS booking_transaction CASCADE;
DROP TABLE IF EXISTS view_hotel_info CASCADE;
DROP TABLE IF EXISTS edit_overall_info CASCADE;
DROP TABLE IF EXISTS manages_booking CASCADE;

DROP TABLE IF EXISTS admin CASCADE;
DROP TABLE IF EXISTS unregisterred_user CASCADE;
DROP TABLE IF EXISTS registerred_user CASCADE;
DROP TABLE IF EXISTS usert CASCADE;

DROP TABLE IF EXISTS hotel CASCADE;
DROP TABLE IF EXISTS hotel_facilities CASCADE;
DROP TABLE IF EXISTS phonenumber CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS room_facilities CASCADE;