-- drop all table at once

DROP TABLE IF EXISTS booking_transaction CASCADE;
DROP TABLE IF EXISTS booking_log CASCADE;
DROP TABLE IF EXISTS hotel_log CASCADE;

DROP TABLE IF EXISTS admin CASCADE;
DROP TABLE IF EXISTS unregisterred_user CASCADE;
DROP TABLE IF EXISTS registerred_user CASCADE;
DROP TABLE IF EXISTS usert CASCADE;

DROP TABLE IF EXISTS hotel CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS room_type_facilities CASCADE;